name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: write
  id-token: write
jobs:
  lint:
    name: Lint
    uses: gofor-little/github-actions/.github/workflows/golang-lint.yaml@main
  test:
    name: Test
    uses: gofor-little/github-actions/.github/workflows/golang-test.yaml@main
    with:
      aws-role: arn:aws:iam::320045747480:role/github-actions
  bump-tag:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs:
      - lint
      - test
    name: Bump Tag
    uses: gofor-little/github-actions/.github/workflows/bump-tag.yaml@d98506bbbf1c1eddb69754f5461f807233ce04e4
  release:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs:
      - bump-tag
    name: Release
    uses: gofor-little/github-actions/.github/workflows/github-release.yaml@main
    with:
      tag: ${{ needs.bump-tag.outputs.bumped-tag }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
